# Site settings
title: Arc Century News
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Reporters Tea, Emma and Matycer follow the arc of OneLife through the centuries.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
